In [100]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [101]:
# load data
df = pd.read_csv('data/bank-full.csv', sep=";")

target_map = {'yes': 1, 'no': 0}
df['y'] = pd.to_numeric(df['y'].map(target_map))

y = df['y']
X = df.drop(columns = ['y'])

df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0  

[5 rows x 21 columns]

In [102]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify=y)

In [103]:
np.unique(y,return_counts=True)

(array([0, 1], dtype=int64), array([36548,  4640], dtype=int64))

In [104]:
print(np.unique(y_train,return_counts=True))
print(np.unique(y_test,return_counts=True))

(array([0, 1], dtype=int64), array([24486,  3109], dtype=int64))
(array([0, 1], dtype=int64), array([12062,  1531], dtype=int64))


In [105]:
train = pd.concat([X_train,y_train],axis=1)
train = train.reset_index().drop(columns=['index'])

test = pd.concat([X_test,y_test],axis=1)
test = test.reset_index().drop(columns=['index'])

train = train.replace('unknown', np.nan)
test = test.replace('unknown', np.nan)

In [108]:
pd.DataFrame.to_csv(train,'data/train.csv', index=False, sep=';')
pd.DataFrame.to_csv(test,'data/test.csv', index=False, sep=';')